"""小说正史仓储的领域端口。

领域 Pipeline 只依赖本协议；正式运行时由 PostgreSQL 实现提供持久化。
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Protocol

from .models import ChapterDraft, ContextTrace, ReviewReport, StoryStateDelta


# 这些阶段只表示“已安全落盘、可从此继续”的 Worker 边界，不等同于 Job 状态。
CHAPTER_CHECKPOINT_STAGES = frozenset(
    {"draft_ready", "review_ready", "revision_ready", "delta_ready"}
)


@dataclass(frozen=True, slots=True)
class ChapterRunCheckpoint:
    """章节运行在一次 Worker 成功后的可恢复快照。"""

    stage: str
    draft_history: tuple[ChapterDraft, ...]
    review_history: tuple[ReviewReport, ...]
    previous_review: ReviewReport | None
    revision_count: int
    context_trace: ContextTrace
    state_delta: StoryStateDelta | None = None

    def __post_init__(self) -> None:
        if self.stage not in CHAPTER_CHECKPOINT_STAGES:
            raise ValueError(f"不支持的章节检查点阶段：{self.stage}")
        if not self.draft_history:
            raise ValueError("章节检查点必须至少包含一份正文")
        if self.revision_count < 0:
            raise ValueError("revision_count 不能小于 0")
        if self.stage == "delta_ready" and self.state_delta is None:
            raise ValueError("delta_ready 检查点必须包含状态增量")


class StoryProjectRepository(Protocol):
    """小说项目、候选计划和章节提交所需的最小仓储能力。"""

    def create_project(self, **kwargs: Any) -> Any: ...
    def load_project(self, book_id: str) -> Any: ...
    def load_project_with_version(self, book_id: str) -> tuple[Any, int]: ...
    def list_projects(self) -> tuple[Any, ...]: ...
    def load_metadata(self, book_id: str) -> Any: ...
    def load_foundation(self, book_id: str) -> Any: ...
    def load_state(self, book_id: str) -> Any: ...
    def load_snapshot(self, book_id: str, chapter_number: int) -> Any: ...
    def load_chapter_index(self, book_id: str) -> tuple[Any, ...]: ...
    def get_next_chapter_number(self, book_id: str) -> int: ...
    def load_chapter_summaries(self, book_id: str) -> tuple[Any, ...]: ...
    def load_chapter(self, book_id: str, chapter_number: int) -> Any: ...
    def load_plan(self, book_id: str, chapter_number: int) -> Any: ...
    def load_delta(self, book_id: str, chapter_number: int) -> Any: ...
    def load_review(self, book_id: str, chapter_number: int, *, final: bool = False) -> Any: ...
    def load_context_trace(self, book_id: str, chapter_number: int) -> Any: ...
    def save_plan_proposal(self, proposal: Any) -> None: ...
    def load_plan_proposal(self, book_id: str, proposal_id: str) -> Any: ...
    def save_chapter_checkpoint(self, proposal: Any, checkpoint: ChapterRunCheckpoint) -> None: ...
    def load_chapter_checkpoint(self, book_id: str, proposal_id: str) -> ChapterRunCheckpoint | None: ...
    def save_chapter_candidate(self, **kwargs: Any) -> Any: ...
    def load_chapter_candidate(self, book_id: str, candidate_id: str) -> Any: ...
    def load_candidate_draft(self, book_id: str, candidate_id: str, *, final: bool = True) -> Any: ...
    def commit_chapter(self, **kwargs: Any) -> Any: ...
    def begin_chapter_rewrite(self, book_id: str, chapter_number: int) -> Any: ...
    def finalize_chapter_rewrite(self, record: Any) -> None: ...
    def rollback_chapter_rewrite(self, record: Any) -> None: ...
