"""应用层持久化端口。正式实现由 SQLite 提供。"""

from __future__ import annotations

from collections.abc import Mapping
from typing import Any, Protocol

from .models import ChatSession, ChatSessionSummary, TimelinePage, TranscriptEvent


class ChatSessionRepository(Protocol):
    """会话及其事件时间线的领域接口。"""

    def create_session(self, *, title: str = "新对话", book_id: str | None = None) -> ChatSession: ...
    def load_session(self, session_id: str) -> ChatSession: ...
    def list_sessions(self) -> tuple[ChatSessionSummary, ...]: ...
    def append_message(self, session_id: str, *, role: str, content: str, action: str = "chat", metadata: Mapping[str, Any] | None = None) -> ChatSession: ...
    def bind_book(self, session_id: str, book_id: str | None, *, allow_nonempty: bool = False) -> ChatSession: ...
    def current_binding_sequence(self, session_id: str) -> int: ...
    def append_event(self, session_id: str, *, event_type: str, payload: Mapping[str, Any] | None = None) -> TranscriptEvent: ...
    def list_events(self, session_id: str) -> tuple[TranscriptEvent, ...]: ...
    def load_timeline(self, session_id: str, *, before_sequence: int | None = None, limit: int = 50) -> TimelinePage: ...
    def latest_summary(self, session_id: str) -> TranscriptEvent | None: ...
    def delete_session(self, session_id: str) -> None: ...
